### ISSUE TITLE
IE7 Error - querySelector

### ISSUE THREAD

**Issue by danielcrisp** [thinktecture/Thinktecture.IdentityServer.v3#778] opened 2015-01-19 13:56 UTC
The use of `querySelector` means I can't login using IE7, which I need to support.

Is it possible to amend the basic JS in `/core/assets/app.FormPostResponse.js` to use something with better support? It is not necessary to use `querySelector` in this situation.

Why not do this? The form will always be present right?

    (function () {
        document.forms[0].submit();
    })();

Or even something like this if you really want to use `querySelector`... (untested)

    (function () {
        if (document.querySelector) {
            document.querySelector('form').submit();
        } else {
            document.forms[0].submit();
        }
    })();

I would add a PR but I can't find the file.

**Comment by brockallen** [comment] 2015-01-19 13:58
We don't support deprecated browsers. IIRC we agreed to IE9 and above.

**Comment by imperugo** [comment] 2015-01-19 14:01
@brockallen probably you are right about deprecated bugs but here is just 1 line of JS. BTW it works with IE8.

**Comment by brockallen** [comment] 2015-01-19 14:01
ok, submit a PR. it's in the default view service's embedded assets folder.

**Comment by imperugo** [comment] 2015-01-19 14:02
cool.

THX

**Comment by johnkors** [comment] 2015-01-19 14:27
Just fyi, Bootstrap supports IE8-11 http://getbootstrap.com/getting-started/#support-browsers

**Comment by imperugo** [comment] 2015-01-19 14:49
@johnkors I know about bootstrap but if you let me to customise the html I can use whatever I want that doesn't mean necessarily bootstrap.

The problem is that "/core/authorize" page is not customisable (am I wrong) and here is just one line of code to have support for all browsers (included the old IE7/8).

**Comment by johnkors** [comment] 2015-01-19 15:48
@imperugo a call to /core/authorize" leads to the login page being rendered, and that is customizable. As is every view defined in the [IViewService](https://github.com/thinktecture/Thinktecture.IdentityServer.v3/blob/master/source/Core/Services/IViewService.cs) interface.

My comment was regarding the default views, which are based on bootstrap.

**Comment by brockallen** [comment] 2015-01-22 02:52
Ok, merged.

**Closed by brockallen** 2015-01-22 02:52 UTC
Labels: question
